import {createInputStore,parseFixture,exportFixture} from './store.js';
import {sampleItems,sampleSequence,SAMPLE_SOURCE} from './fixtures.js';
import {fetchGmailInbox,fetchLastfm,fetchWeather,searchLocations} from './providers.js';
import {createGmailSession,loadGoogleIdentity} from './gmail-auth.js';
import {createSourceLifecycle} from './lifecycle.js';
import {createPublicSession} from './public-session.js';
import {publicMarkup,createPublicView} from './public-view.js';

const markup=`
<div class="sources-heading"><div><span class="eyebrow">What moves the flock</span><h2>Sources</h2></div><button id="sources-close" class="icon-button" aria-label="Close sources" type="button">×</button></div>
<p class="sources-intro">A message becomes a bird. A reply changes its movement. Choose a sample, your own connections or a flock fed by the public world.</p>
<div class="source-modes" role="group" aria-label="Choose data shown"><button id="mode-sample" type="button" aria-pressed="true">Sample flock</button><button id="mode-public" type="button" aria-pressed="false">Public world</button><button id="mode-live" type="button" aria-pressed="false">My sources</button></div>
<p id="sources-summary" class="source-summary" aria-live="polite"></p>
${publicMarkup}
<section class="source-card"><div class="source-card-heading"><h3>Sample activity</h3><span class="source-badge">Local only</span></div><p>Fictional mail, agent conversations and shared documents. Replay arrivals, a repeated delivery, a read and an archive.</p><div class="source-actions"><button id="sample-replay" type="button">Replay activity</button><button id="sample-reset" type="button">Reset sample</button></div><p id="sample-status" class="source-status" aria-live="polite">36 fictional items. No accounts connected.</p><details><summary>Import or export a fixture</summary><p>Files stay in this browser tab. Only item metadata is used; message bodies and credentials are discarded. An export may contain personal IDs and titles. Keep it private.</p><label class="file-label" for="fixture-import">Import metadata JSON</label><input id="fixture-import" type="file" accept=".json,application/json"><button id="fixture-export" type="button">Export visible metadata</button></details></section>
<section class="source-card"><div class="source-card-heading"><h3>Gmail</h3><span id="gmail-badge" class="source-badge">Setup required</span></div><p>One bird per Inbox message, up to 2,000. Unread messages have a centre dot; reading clears it. Archives remove their bird. Subjects, senders and message bodies are not requested.</p><label for="gmail-client">Google OAuth client ID</label><input id="gmail-client" type="text" autocomplete="off" spellcheck="false" placeholder="…apps.googleusercontent.com"><div class="source-actions"><button id="gmail-connect" type="button">Load Google sign-in</button><button id="gmail-refresh" type="button" disabled>Refresh</button><button id="gmail-disconnect" type="button" disabled>Disconnect</button></div><p id="gmail-status" class="source-status" aria-live="polite">Requires your Google OAuth web client. Reconnect after reload or token expiry. Refreshes once a minute while this page is visible.</p><details><summary>Set up Gmail</summary><ol><li>Enable the Gmail API in a Google Cloud project.</li><li>Create an OAuth web client and add this exact origin: <code id="gmail-origin"></code></li><li>Configure the consent screen, add yourself as a test user, and allow the Gmail metadata scope.</li><li>Paste the public client ID above. Load sign-in, then connect.</li></ol><p>Authorization stays in memory. There is no background sync or server storage. Disconnect stops requests and leaves the last flock in this tab; Forget Gmail removes it. Google’s restricted-scope requirements apply if you distribute this beyond a personal pilot.</p><div class="source-actions"><button id="gmail-forget" type="button">Forget Gmail metadata</button><button id="gmail-revoke" type="button">Revoke Google access</button></div><a href="https://developers.google.com/identity/oauth2/web/guides/use-token-model" target="_blank" rel="noopener noreferrer">Google token flow documentation ↗</a></details></section>
<section class="source-card"><div class="source-card-heading"><h3>Weather</h3><span id="weather-badge" class="source-badge">Choose a city</span></div><p>Wind, cloud and daylight shape the atmosphere. Search a city to use current public observations.</p><form id="weather-search"><label for="weather-city">City</label><div class="input-action"><input id="weather-city" type="search" autocomplete="off" placeholder="Search for a city" minlength="2" required><button type="submit">Search</button></div></form><div id="weather-results" class="location-results"></div><div class="source-actions"><button id="weather-refresh" type="button" disabled>Refresh weather</button><button id="weather-disconnect" type="button" disabled>Clear weather</button></div><p id="weather-status" class="source-status" aria-live="polite">No location selected. Refreshes every 15 minutes; observations expire after 30 minutes.</p><a href="https://open-meteo.com/" target="_blank" rel="noopener noreferrer">Weather data by Open-Meteo ↗</a></section>
<section class="source-card"><div class="source-card-heading"><h3>Last.fm</h3><span id="music-badge" class="source-badge">Setup required</span></div><p>Listening reported to Last.fm affects the atmosphere. Recorded plays create brief activity without adding permanent birds.</p><label for="music-user">Last.fm username</label><input id="music-user" type="text" autocomplete="off" spellcheck="false"><label for="music-key">Last.fm API key</label><input id="music-key" type="password" autocomplete="off" spellcheck="false"><div class="source-actions"><button id="music-connect" type="button">Connect Last.fm</button><button id="music-refresh" type="button" disabled>Refresh</button><button id="music-disconnect" type="button" disabled>Disconnect</button></div><p id="music-status" class="source-status" aria-live="polite">Username and API key are held only in memory. Refreshes every 30 seconds while visible. Reconnect after reload.</p><a href="https://www.last.fm/api/account/create" target="_blank" rel="noopener noreferrer">Get a Last.fm API key ↗</a></section>
<section class="source-card"><div class="source-card-heading"><h3>X / Twitter</h3><span class="source-badge">Setup required</span></div><p>The server adapter is ready for a chosen search feed. Paid requests are disabled. It needs a server-held bearer token, owner authentication and an approved provider budget before it can connect.</p><p class="source-status">No X requests are sent by this site.</p></section>
<section class="source-card"><div class="source-card-heading"><h3>Documents, agents and Slack</h3><span class="source-badge">Fixture import</span></div><p>Import metadata using the shared item format to try these sources now. Live connectors require the specific product, account permissions and an integration route. Consumer Claude exports are historical records.</p></section>`;

export function mountSources({onState=()=>{},notice=()=>{},onOpen=()=>{}}={}) {
  const panel=document.createElement('aside');panel.id='sources';panel.className='sources interface';panel.hidden=true;panel.setAttribute('aria-label','Activity sources');panel.innerHTML=markup;document.querySelector('main').append(panel);
  const $=id=>document.getElementById(id);
  $('gmail-origin').textContent=location.origin;
  let sample=createInputStore(),live=createInputStore(),mode='sample',replay=null,step=0,sequence=[],fixtureName='Sample flock';
  const states={gmail:{status:'Setup required',message:''},weather:{status:'Choose a city',message:''},music:{status:'Setup required',message:''}};
  const pending={gmail:false,weather:false,music:false,search:false};
  const epochs={gmail:0,weather:0,music:0,search:0};
  let lastGmail=0,lastWeather=0,lastMusic=0,gmailSources=new Set(),musicUser='',musicKey='',weatherLocation=null;
  const controllers={};
  function cancel(kind){epochs[kind]++;controllers[kind]?.abort();pending[kind]=false;}
  const publicView=createPublicView(panel);
  const publicSession=createPublicSession({onChange(state){publicView.update(state);if(mode==='public')emit();}});
  function current(){return mode==='public'?publicSession:mode==='sample'?sample:live;}
  function sourceStatus(kind,status,message){states[kind]={status,message};$(`${kind==='music'?'music':kind}-badge`).textContent=status;$(`${kind}-status`).textContent=message;emit();}
  function emit(){
    const state=current().getState();
    const liveEnvironment=live.getState().environment;
    const liveAtmosphere=mode==='sample'&&fixtureName==='Sample flock'&&Boolean(liveEnvironment.weather||liveEnvironment.listening);
    if(liveAtmosphere)state.environment={...state.environment,...liveEnvironment};
    const liveCount=mode==='public'?state.sources.filter(value=>value.status==='live').length:Object.values(states).filter(value=>value.status==='Live').length;
    const label=mode==='public'?'Public world':mode==='sample'?fixtureName:'My sources';
    $('public-world').hidden=mode!=='public';
    for(const card of panel.querySelectorAll('.source-card:not(.public-card)'))card.hidden=mode==='public';
    $('mode-public').setAttribute('aria-pressed',String(mode==='public'));
    $('sources-summary').textContent=`${label} · ${state.items.length} items · ${mode==='public'?`${liveCount} current public feeds`:mode==='sample'?(liveAtmosphere?'sample items, live atmosphere':'fictional or imported metadata'):`${liveCount} live connection${liveCount===1?'':'s'}`}`;
    $('mode-sample').setAttribute('aria-pressed',String(mode==='sample'));$('mode-live').setAttribute('aria-pressed',String(mode==='live'));
    onState({...state,mode,liveAtmosphere,label,liveCount});
  }
  function setMode(next){mode=next;if(mode==='public'&&!document.hidden)publicSession.start();else publicSession.suspend();emit();}
  $('public-city').addEventListener('change',event=>publicSession.setCity(event.target.value));
  document.addEventListener('visibilitychange',()=>{if(document.hidden)publicSession.suspend();else if(mode==='public')publicSession.start();});
  function resetSample(){clearInterval(replay);replay=null;sample=createInputStore();const now=Date.now();sample.applySnapshot(SAMPLE_SOURCE,sampleItems(now),{revision:now,now});fixtureName='Sample flock';$('sample-status').textContent='36 fictional items. No accounts connected.';$('sample-replay').textContent='Replay activity';setMode('sample');}
  function close({focus=true}={}){panel.hidden=true;$('sources-toggle').setAttribute('aria-expanded','false');if(focus)$('sources-toggle').focus();}
  function open(){onOpen();panel.hidden=false;$('sources-toggle').setAttribute('aria-expanded','true');$('sources-close').focus();}
  $('sources-close').addEventListener('click',close);
  $('sources-toggle').addEventListener('click',()=>panel.hidden?open():close());
  panel.addEventListener('keydown',event=>{if(event.key==='Escape'){event.stopPropagation();close();}});
  $('mode-public').addEventListener('click',()=>setMode('public'));
  $('mode-sample').addEventListener('click',()=>setMode('sample'));$('mode-live').addEventListener('click',()=>setMode('live'));
  $('sample-reset').addEventListener('click',resetSample);
  $('sample-replay').addEventListener('click',()=>{
    if(replay){clearInterval(replay);replay=null;$('sample-replay').textContent='Replay activity';return;}
    resetSample();const now=Date.now();sequence=sampleSequence(sample.getState().items,now);step=0;$('sample-replay').textContent='Stop replay';
    replay=setInterval(()=>{const entry=sequence[step++];sample.applyChanges(entry.changes,Date.now());$('sample-status').textContent=entry.label;emit();if(step===sequence.length){clearInterval(replay);replay=null;$('sample-replay').textContent='Replay activity';}},1000);
  });
  $('fixture-import').addEventListener('change',async event=>{
    const file=event.target.files?.[0];if(!file)return;
    try {if(file.size>1_000_000)throw new Error('Fixture must be smaller than 1 MB.');const fixture=parseFixture(await file.text());const next=createInputStore();const now=Date.now();next.applyChanges(fixture.items.map(item=>({eventId:`import:${item.itemId}`,sourceId:item.sourceId,itemId:item.itemId,type:'upsert',item,revision:item.revision})),now);next.applyChanges(fixture.changes,now);for(const [kind,value]of Object.entries(fixture.environment))next.setEnvironment(kind,value);clearInterval(replay);replay=null;sample=next;fixtureName='Imported local fixture';$('sample-status').textContent=`Imported ${fixture.items.length} metadata items. This file stays in the current tab.`;$('sample-replay').textContent='Replay activity';setMode('sample');}
    catch(error){notice(error.message);$('sample-status').textContent=error.message;}
    event.target.value='';
  });
  $('fixture-export').addEventListener('click',()=>{const data=exportFixture(current().getState());const url=URL.createObjectURL(new Blob([data],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='murmuration-metadata.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('Metadata exported locally. Keep personal fixture files private.');});

  const gmail=createGmailSession({onToken(){sourceStatus('gmail','Connecting','Reading Inbox metadata…');refreshGmail(true);},onError(error){sourceStatus('gmail','Not connected',error.message);}});
  async function refreshGmail(activate=false){
    if(pending.gmail)return;const epoch=epochs.gmail;pending.gmail=true;controllers.gmail=new AbortController();$('gmail-refresh').disabled=true;
    try{const result=await fetchGmailInbox(gmail.getToken(),{signal:controllers.gmail.signal});if(epoch!==epochs.gmail)return;const now=Date.now();live.applySnapshot(result.sourceId,result.items,{revision:now,now});gmailSources.add(result.sourceId);live.setSourceState(result.sourceId,{status:'live',lastSeenAt:now});lastGmail=now;sourceStatus('gmail','Live',`${result.items.length} Inbox messages · refreshed ${new Date(now).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}. No subjects or bodies stored.`);$('gmail-disconnect').disabled=false;if(activate)setMode('live');}
    catch(error){if(epoch!==epochs.gmail)return;if(error.status===401)gmail.disconnect();sourceStatus('gmail',gmail.hasToken()?'Unavailable':'Reconnect required',error.message);lastGmail=Date.now()+(error.retryAfterMs??0);}
    finally{if(epoch===epochs.gmail){pending.gmail=false;$('gmail-refresh').disabled=!gmail.hasToken();}}
  }
  $('gmail-connect').addEventListener('click',async()=>{
    try{const clientId=$('gmail-client').value.trim();if(!clientId)throw new Error('Enter your public Google OAuth client ID first.');if(!globalThis.google?.accounts?.oauth2){$('gmail-connect').disabled=true;await loadGoogleIdentity();$('gmail-connect').textContent='Connect Gmail';sourceStatus('gmail','Ready to connect','Google sign-in is ready. Click Connect Gmail to authorize this browser tab.');return;}cancel('gmail');gmail.connect(clientId);$('gmail-disconnect').disabled=false;sourceStatus('gmail','Connecting','Complete Google sign-in in the new window.');}
    catch(error){sourceStatus('gmail','Setup required',error.message);}finally{$('gmail-connect').disabled=false;}
  });
  function disconnectGmail(){cancel('gmail');gmail.disconnect();for(const source of gmailSources)live.setSourceState(source,{status:'disconnected'});$('gmail-refresh').disabled=true;$('gmail-disconnect').disabled=true;sourceStatus('gmail','Disconnected','Requests stopped. Last Inbox metadata remains in this tab until forgotten or reloaded.');}
  $('gmail-refresh').addEventListener('click',()=>refreshGmail(true));$('gmail-disconnect').addEventListener('click',()=>disconnectGmail());$('gmail-revoke').addEventListener('click',async()=>{cancel('gmail');const result=gmail.revoke();$('gmail-refresh').disabled=true;$('gmail-disconnect').disabled=true;$('gmail-revoke').disabled=true;$('gmail-connect').disabled=true;try{await result;sourceStatus('gmail','Disconnected','Google confirmed access was revoked. Last Inbox metadata remains until forgotten or reloaded.');}catch(error){sourceStatus('gmail','Disconnected',error.message);}finally{$('gmail-revoke').disabled=false;$('gmail-connect').disabled=false;}});
  $('gmail-forget').addEventListener('click',()=>{disconnectGmail();for(const source of gmailSources)live.forgetSource(source);gmailSources.clear();sourceStatus('gmail','Disconnected','Gmail metadata forgotten. Reconnect to read the Inbox again.');});

  async function refreshWeather(){
    if(!weatherLocation||pending.weather)return;const epoch=epochs.weather;pending.weather=true;controllers.weather=new AbortController();$('weather-refresh').disabled=true;
    try{const value=await fetchWeather(weatherLocation,{signal:controllers.weather.signal});if(epoch!==epochs.weather)return;live.setEnvironment('weather',value);lastWeather=Date.now();sourceStatus('weather','Live',`${value.location} · ${Math.round(value.temperatureC)}°C · wind ${Math.round(value.windKph)} km/h · ${Math.round(value.cloudCover*100)}% cloud. Observed ${new Date(value.observedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}.`);$('weather-disconnect').disabled=false;}
    catch(error){if(epoch!==epochs.weather)return;lastWeather=Date.now()+(error.retryAfterMs??0);sourceStatus('weather','Unavailable',error.message+' Fresh previous conditions stay until expiry.');}
    finally{if(epoch===epochs.weather){pending.weather=false;$('weather-refresh').disabled=!weatherLocation;}}
  }
  $('weather-search').addEventListener('submit',async event=>{event.preventDefault();const query=$('weather-city').value.trim();if(query.length<2)return;cancel('search');const epoch=epochs.search;controllers.search=new AbortController();$('weather-results').replaceChildren();sourceStatus('weather','Searching','Searching for matching cities…');try{const results=await searchLocations(query,{signal:controllers.search.signal});if(epoch!==epochs.search)return;for(const result of results){const button=document.createElement('button');button.type='button';button.textContent=[result.name,result.region,result.country].filter(Boolean).join(', ');button.addEventListener('click',()=>{cancel('weather');weatherLocation=result;$('weather-results').replaceChildren();refreshWeather();});$('weather-results').append(button);}sourceStatus('weather',results.length?'Choose a city':'No matches',results.length?'Select the city you want to use.':'Try a nearby city or a longer name.');}catch(error){if(epoch===epochs.search)sourceStatus('weather','Unavailable',error.message);}});
  $('weather-refresh').addEventListener('click',()=>refreshWeather());$('weather-disconnect').addEventListener('click',()=>{cancel('weather');weatherLocation=null;live.setEnvironment('weather',null);$('weather-refresh').disabled=true;$('weather-disconnect').disabled=true;sourceStatus('weather','Choose a city','Weather cleared. No location selected.');});

  async function refreshMusic(){
    if(!musicKey||pending.music)return;const epoch=epochs.music;pending.music=true;controllers.music=new AbortController();$('music-refresh').disabled=true;
    try{const value=await fetchLastfm(musicUser,musicKey,{signal:controllers.music.signal});if(epoch!==epochs.music)return;live.applyChanges(value.changes);live.setEnvironment('listening',value.listening);lastMusic=Date.now();sourceStatus('music','Live',value.listening.playing?`Now playing: ${value.listening.artist} — ${value.listening.track}`:`Connected to ${musicUser}. Nothing currently reported as playing.`);$('music-disconnect').disabled=false;}
    catch(error){if(epoch!==epochs.music)return;lastMusic=Date.now()+(error.retryAfterMs??0);sourceStatus('music','Unavailable',error.message+' Listening clears after 90 seconds without a fresh observation.');}
    finally{if(epoch===epochs.music){pending.music=false;$('music-refresh').disabled=!musicKey;}}
  }
  $('music-connect').addEventListener('click',()=>{const username=$('music-user').value.trim(),key=$('music-key').value.trim();if(!username||!key){sourceStatus('music','Setup required','Enter a Last.fm username and API key.');return;}cancel('music');live.setEnvironment('listening',null);musicUser=username;musicKey=key;$('music-disconnect').disabled=false;sourceStatus('music','Connecting','Reading recent listening…');$('music-key').value='';refreshMusic();});
  $('music-refresh').addEventListener('click',()=>refreshMusic());$('music-disconnect').addEventListener('click',()=>{cancel('music');musicKey='';musicUser='';$('music-key').value='';live.setEnvironment('listening',null);$('music-refresh').disabled=true;$('music-disconnect').disabled=true;sourceStatus('music','Disconnected','Last.fm credentials and current listening cleared.');});
  function tick(){if(mode==='public')publicSession.start();const now=Date.now();if(gmail.hasToken()&&now-lastGmail>=60_000)refreshGmail();if(weatherLocation&&now-lastWeather>=900_000)refreshWeather();if(musicKey&&now-lastMusic>=30_000)refreshMusic();if(['Live','Unavailable'].includes(states.gmail.status)&&!gmail.hasToken()){sourceStatus('gmail','Reconnect required','Authorization expired. Reconnect Gmail; last Inbox metadata is still shown.');$('gmail-refresh').disabled=true;}const env=live.getState(now).environment;if(states.weather.status==='Live'&&!env.weather)sourceStatus('weather','Stale','Weather observation expired. Calm fallback until the next refresh.');if(states.music.status==='Live'&&!env.listening)sourceStatus('music','Stale','Listening observation expired. Waiting for a fresh report.');emit();}
  createSourceLifecycle({tick,suspend(){publicSession.suspend();clearInterval(replay);replay=null;$('sample-replay').textContent='Replay activity';for(const kind of Object.keys(epochs))cancel(kind);$('gmail-refresh').disabled=!gmail.hasToken();$('weather-refresh').disabled=!weatherLocation;$('music-refresh').disabled=!musicKey;},dispose(){publicSession.dispose();gmail.disconnect();musicKey='';}});
  resetSample();if(new URLSearchParams(location.search).get('sources')==='public')setMode('public');return {getState:()=>({...current().getState(),mode}),open,close,setCity:id=>publicSession.setCity(id)};
}
